services:
  - type: web
    name: taxi-zones-clinifio
    runtime: python
    region: oregon
    plan: free
    buildCommand: python -m pip install --upgrade pip && pip install --prefer-binary -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
